# Generated by Django 4.1.1 on 2022-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaReserva',
            fields=[
                ('id_consulta_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=45)),
                ('motivo_consulta', models.CharField(max_length=45)),
                ('peso', models.FloatField()),
            ],
            options={
                'db_table': 'consulta_reserva',
                'managed': False,
            },
        ),
    ]
