# Generated by Django 4.1.1 on 2022-12-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=24)),
                ('contrasena', models.CharField(max_length=34)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
