# Generated by Django 4.1.1 on 2022-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id_veterinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vet', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254, verbose_name='Tu correo electrónico')),
                ('descripcion', models.TextField(max_length=499)),
            ],
            options={
                'db_table': 'veterinaria',
                'managed': False,
            },
        ),
    ]
