# Generated by Django 4.1.1 on 2022-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_procedimiento', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'procedimiento',
                'managed': False,
            },
        ),
    ]
