# Generated by Django 4.1.1 on 2022-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaProcedimiento',
            fields=[
                ('id_consulta_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(max_length=3000)),
            ],
            options={
                'db_table': 'consulta_procedimiento',
                'managed': False,
            },
        ),
    ]
