# Generated by Django 4.1.1 on 2022-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoHora',
            fields=[
                ('id_estado_hora', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'estado_hora',
                'managed': False,
            },
        ),
    ]
